name: alphazero
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.3.1
  - numpy=1.22.3
  - pip=21.2.4
  - python=3.10.5
  - pytorch=1.11.0
  - scikit-learn=1.0.2
  - pip:
      - gym==0.11.0
      - boardgame2==0.0.5
      - tqdm==4.64.0